= Hardware specifications

Where did your run your tests? A laptop, or goldengate?
- I ran my tests on a personal laptop with ssh to goldengate.

What are the performance specifications of the machine: number and speed of
processors, size of RAM? (use `lscpu` and `free -m`)
- machine is running on x86_64 with 64 CPUs (32-bit and 64-bit). CPU ~4000 MHz, with a
    max of 4100 MHz and a min of 1200 MHz. Total amount of RAM is 95315 megabytes, with
    86823 megabytes free.

= Single-process mandelbrot

Run your executable, `single_mandelbrot`, with the following sizes and record
the amount of time it takes to compute each image.

[cols="1,1"]
!===
| Size | Time (s) 
| 100 | todo
| 400 | todo
| 800 | todo
| 1000 | todo
| 2000 | todo
!===

= Multi-process mandelbrot

Run your executable, `multi_mandelbrot`, with the following sizes and record
the amount of time it takes to compute each image.

[cols="1,1"]
!===
| Size | Time (s) 
| 100 | todo
| 400 | todo
| 800 | todo
| 1000 | todo
| 2000 | todo
!===
